services:
- type: web
  name: ai-trader-backend
  runtime: python
  plan: starter
  region: virginia
  branch: feat/option-a-cloud-backend
  rootDir: backend
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  envVars:
    - key: API_TOKEN
      sync: false
    - key: ALLOW_ORIGIN
      value: https://ai-trader-snowy.vercel.app
    - key: LIVE_TRADING
      value: "false"
    - key: REDIS_URL
      sync: false